name: nexus_live_view
description: Premium restaurant management live view for tablet and mobile.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.4.3
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
